version: "3.2"
services:
  web:
    build: .
    volumes:
      - ./src:/var/www/html
    ports:
      - 8888:80
    environment:
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - ./volumes/database:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: REGISTRATION_DB
      MYSQL_USER: far
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
